# This Azure Pipeline runs unit and integration tests.
# This pipeline is triggered upon making a PR against the main branch.
# Unit tests are defined under project1/tests
# and are executed on the Azure Pipelines agent.
# The integration tests deploys and runs the model_training_job defined in project1/resources/model-workflow-resource.yml
# This integration tests is run in the staging workspace, as defined under project1/databricks.yml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - project1/*
      - '.azure/devops-pipelines/project1-run-tests.yml'

variables:
  - name: workingDirectory
    value: project1
  - group: my-monorepo

jobs:
  - job: UnitTests
    displayName: 'Unit Tests'
    # Trigger unit tests upon making a PR against the main branch
    condition: |
      and(
        not(eq(variables['Build.Reason'], 'IndividualCI')),
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
      )
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8

    - script: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r project1/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pytest --junitxml=test-unit.xml
      displayName: 'Run unit tests with pytest'

  - job: IntegrationTests
    displayName: 'Integration Tests'
    # Integration tests will only run upon unit tests successfully passing
    dependsOn: UnitTests
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.225.0/install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Extract Databricks version to tests installation
    - script: |
        databricks version
      displayName: 'Get Databricks CLI version'

    # Validate bundle to be deployed to the staging workspace
    - script: |
        databricks bundle validate -t udhay_mlops_stg
      workingDirectory: $(workingDirectory)
      displayName: Validate bundle for tests deployment target in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        

    # Deploy bundle to staging workspace
    - script: |
        databricks bundle deploy -t udhay_mlops_stg
      workingDirectory: $(workingDirectory)
      displayName: Deploy bundle to tests deployment target in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        

    

    # Run model_training_job defined in bundle in the staging workspace
    - script: |
        databricks bundle run model_training_job -t udhay_mlops_stg
        databricks bundle run model_infernce_job -t udhay_mlops_stg --var=input_table="subsample_data"
      workingDirectory: $(workingDirectory)
      displayName: Run training workflow for tests deployment target in staging workspace
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        
