# This Azure Pipeline validates and deploys bundle config (ML resource config and more)
# defined under project1/resources/*
# and project1/databricks.yml.
# The bundle is validated (CI) upon making a PR against the main branch.
# Bundle resources defined for staging are deployed when a PR is merged into the main branch.
# Bundle resources defined for prod are deployed when a PR is merged into the release branch.

trigger:
  branches:
    include:
      - main
      - release
  paths:
    include:
      - project1/*

variables:
  - name: workingDirectory
    value: project1
  - group: my-monorepo variable group

stages:
# Run BundleCI stage upon making a PR against the main branch
- stage: BundleCI
  displayName: 'Bundle validation for project1'
  # Trigger BundleCI stage on PR against the default branch, and not on pushes to other branches
  condition: |
    and(
      not(eq(variables['Build.Reason'], 'IndividualCI')),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')
    )

  jobs:
  - job: StagingBundleCI
    displayName: 'Staging bundle validation for project1'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli//install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Validate bundle to be deployed to the staging workspace
    - script: |
        databricks bundle validate -t udhay_mlops_stg
      workingDirectory: $(workingDirectory)
      displayName: 'Validate bundle for staging'
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        


  - job: prodBundleCI
    displayName: 'Prod bundle validation for project1'
    dependsOn: []   # Removes the implicit dependency on previous job and force prodBundleCI job to run in parallel

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

    # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli//install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Validate bundle to be deployed to the prod workspace
    - script: |
        databricks bundle validate -t prod
      workingDirectory: $(workingDirectory)
      displayName: 'Validate bundle for prod'
      env:
        ARM_TENANT_ID: $(PROD_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(PROD_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(PROD_AZURE_SP_CLIENT_SECRET)
        

# Run StagingBundleCD stage after successfully merging into the main branch
- stage: StagingBundleCD
  displayName: 'Staging bundle deployment for project1'
  # Trigger deployment of bundle resources when PRs are merged into the main branch
  condition: |
    and(
      eq(variables['Build.SourceBranch'], 'refs/heads/main'),
      not(eq(variables['Build.Reason'], 'PullRequest'))
    )

  jobs:
  - job: StagingBundleCD
    displayName: 'Bundle Deployment for project1 Staging'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

      # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli//install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Validate bundle to be deployed to the Staging workspace
    - script: |
        databricks bundle validate -t udhay_mlops_stg
      workingDirectory: $(workingDirectory)
      displayName: 'Validate bundle for staging'
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        

    # Deploy bundle to Staging workspace
    - script: |
        databricks bundle deploy -t udhay_mlops_stg
      workingDirectory: $(workingDirectory)
      displayName: 'Deploy bundle to staging'
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        

# Run prod bundle CD stage after successfully merging into the release branch
- stage: prodBundleCD
  displayName: 'Prod bundle deployment for project1'
  # Trigger deployment of Bundle resources when PRs are merged into the release branch
  condition: |
    and(
      eq(variables['Build.SourceBranch'], 'refs/heads/release'),
      not(eq(variables['Build.Reason'], 'PullRequest'))
    )

  jobs:
  - job: prodBundleCD
    displayName: 'Bundle deployment for project1 prod'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

      # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli//install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Validate bundle to be deployed to the prod workspace
    - script: |
        databricks bundle validate -t prod
      workingDirectory: $(workingDirectory)
      displayName: 'Validate bundle for prod'
      env:
        ARM_TENANT_ID: $(PROD_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(PROD_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(PROD_AZURE_SP_CLIENT_SECRET)
        

    # Deploy bundle to prod workspace
    - script: |
        databricks bundle deploy -t prod
      workingDirectory: $(workingDirectory)
      displayName: 'Deploy bundle to prod'
      env:
        ARM_TENANT_ID: $(PROD_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(PROD_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(PROD_AZURE_SP_CLIENT_SECRET)
        
